Repository RoDaMo/pds-front-end, pull requests merged in 2023-05, with the labels that each got.

#28 PR: Issue #25 [Refatorar Home]
  index.html
  js/home.js
  js/i18n/ptbr/main.json
  js/utilidades/header.js
  js/utilidades/swiped-events.min.js
  package-lock.json
  package.json
  public/Home_Player.png
  public/icons/sports_soccer.svg
  public/icons/sports_volleyball.svg
  public/rodamoLogo.png
  scss/bootstrap-config.scss
  scss/styles.scss
Labels: enhancement

#33 Revisão de adições
  index.html
  js/cadastro-usuarios.js
  js/home.js
  js/login.js
  js/utilidades/header.js
  package-lock.json
  pages/cadastro-usuarios.html
  pages/home.html
  pages/login.html
  scss/bootstrap-config.scss
  scss/home.scss
  scss/styles.scss
  vite.config.js
Labels: bug

#40 Home e novas páginas
  .gitignore
  index.html
  js/cadastro-usuarios.js
  js/home.js
  js/i18n/ptbr/main.json
  js/login.js
  js/utilidades/configFetch.js
  js/utilidades/header.js
  js/utilidades/swiped-events.min.js
  js/utilidades/visualizar-senha.js
  main.js
  package-lock.json
  package.json
  pages/cadastro-usuarios.html
  pages/home.html
  pages/login.html
  public/Home_Player.png
  public/icons/sports_soccer.svg
  public/icons/sports_volleyball.svg
  public/rodamoLogo.png
  scss/bootstrap-config.scss
  scss/home.scss
  scss/styles.scss
  vite.config.js
Labels: bug, enhancement
